### ISSUE TITLE
example with EPSG:32639

### ISSUE THREAD

**Issue by vahid-sohrabloo** [kartena/Proj4Leaflet#10]
Hi 
I need one example with  EPSG:32639. I try use this crs. but problem
Very thanks

**Comment by perliedman** [comment]
Hi,
I would need some more detail on your setup to give you some useful feedback. Since I don't have any tile set in EPSG:32639, I can't really make a working example.

I might suggest that you read my write-up on tiling maps and projections: http://www.liedman.net/tiled-maps/

I'm closing this issue for now, but you're welcome to add more comments if you have further questions.

**Comment by ijustloveit13** [comment]
Dear perliedman
EPSG:32639 is UTM zone 39.
Is there any way to define a crs with the aforementioned properies?

**Comment by perliedman** [comment]
@ijustloveit13 it's definitely supported, but the exact parameters depends a lot on the tile set in question: primarily its origin and the scales/resolutions for its zoom levels.
