### ISSUE TITLE
Using Leaflet.timeline and Proj4Leaflet

### ISSUE THREAD

**Issue by krillmcrawl** [kartena/Proj4Leaflet#152]
Hi!

I'm using https://github.com/skeate/Leaflet.timeline. I want to load a geojson file using crs EPSG:3011. Normally this works great using your plugin. 

And since since L.Timeline is a subclass of L.GeoJSON i thought that this would work:
L.Proj.Timeline

But that will throw an error like this "Uncaught TypeError: L.Proj.timeline is not a function"

Anyone got any experience the two systems working together?

Best Regards,

Kristian

**Comment by basisbit** [comment]
please provide a jsfiddle link or similar, so we can reproduce the problem

**Comment by perliedman** [comment]
Hi, I'm agreeing with @basisbit - if you believe this is still an issue, please:

* provide a description of what problem you're actually seeing (it's not clear to me after reading the comment above)
* set up an example illustrating the problem on for example jsfiddle or codepen

Not trying to be complicated, but please realize that the time available for maintaining this project is limited, and although unfortunate, issues without a clear description or that requires time for us to even understand the problem is likely to be left untouched.
