### ISSUE TITLE
How i can convert geoJSON to different projection? 

### ISSUE THREAD

**Issue by PawelGIX** [kartena/Proj4Leaflet#174]
Is there any example?
I'm looking for something like 
`projection(fromProjection[, toProjection, geoJSON])`

**Comment by perliedman** [comment]
Is this for display on a Leaflet map? The you should use [`L.Proj.GeoJSON`](https://github.com/kartena/Proj4Leaflet#lprojgeojson).

Otherwise, if you are looking to actually reprojecting the GeoJSON to another GeoJSON object with reprojected coordinates, please have a look at [reproject](https://github.com/perliedman/reproject/)
